# Generated by Django 4.1.3 on 2022-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_role_alter_users_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('moderator', 'moderator'), ('admin', 'admin'), ('user', 'user'), ('unknown', 'unknown')], default='unknown', max_length=40, null=True),
        ),
    ]
